name: Job Resolution Tests

on:
  workflow_dispatch: # allows manual triggering
  workflow_call: # allows call from another workflow

jobs:
  job1:
    runs-on: ubuntu-22.04
    steps:
    - name: Debug
      shell: bash
      run: |
        echo "Job 1"

  job2:
    runs-on: ubuntu-22.04
    env:
      CC: clang
    steps:
    - name: Debug
      shell: bash
      run: |
        echo "Job 2"

  job3:
    runs-on: ubuntu-22.04
    steps:
    - name: Debug
      shell: bash
      run: |
        echo "Job 3"
        exit 1

  all_tests:
    runs-on: ubuntu-22.04
    needs: [job1, job2, job3]
    if: ${{ always() }}
    steps:
      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


